import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@ecommerce/ui/src/app/globals.css';

const montserretFont = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserretFont.className} antialiased`}>{children}</body>
    </html>
  );
}
