name: Build and Push Docker Images

on:
  push:
    tags:
      - v*  # Trigger on version tags like v1.0.0

jobs:
  build-api:
    name: Build and Push API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: |
            sa2avroo/ecommerce-server-node:latest
            sa2avroo/ecommerce-server-node:${{ github.sha }}
            sa2avroo/ecommerce-server-node:${{ github.ref_name }}
      - name: Logout from Docker Hub
        run: docker logout

  build-web:
    name: Build and Push Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: |
            sa2avroo/ecommerce-web-nextjs:latest
            sa2avroo/ecommerce-web-nextjs:${{ github.sha }}
            sa2avroo/ecommerce-web-nextjs:${{ github.ref_name }}
      - name: Logout from Docker Hub
        run: docker logout


  build-admin:
    name: Build and Push Admin App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Admin Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/admin/Dockerfile
          push: true
          tags: |
            sa2avroo/ecommerce-admin-nextjs:latest
            sa2avroo/ecommerce-admin-nextjs:${{ github.sha }}
            sa2avroo/ecommerce-admin-nextjs:${{ github.ref_name }}

      - name: Logout from Docker Hub
        run: docker logout